### ISSUE TITLE
S3 region Frankfurt error: The authorization mechanism you have provided is not supported

### ISSUE THREAD

**Issue by naabster** [timkay/aws#91]
I get the following error when I try to access a S3 bucket in the new Frankfurt region:

307 Temporary Redirect
+----------------+----------------------------------------------------------------------------------------------+------------------+
|      Code      |                                           Message                                            |    RequestId     |
+----------------+----------------------------------------------------------------------------------------------+------------------+
| InvalidRequest | The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. | 5899A2581461XXXX |
+----------------+----------------------------------------------------------------------------------------------+------------------+

**Comment by timkay** [comment]
Try using the latest signature algorithm by adding `--AWS4` to the command line.

If it works, then you can add `--AWS4` to `~/.awsrc` .

If it doesn't work, let me know, and we'll sort it out.

...Tim

**Comment by naabster** [comment]
It works with adding `--AWS4 --region='eu-central-1'` to the command line.

thanks!
